#!/usr/bin/env bash
#
# $$ GPGKITTY $$
# $$ cheap gpg magic for sexual powress $$
#
# decrypt a message file
#

. ./gpg-kitty

if [ -z "$1" ]; then
  usage; exit 1
fi
if [ -z "$2" ]; then
  usage; exit 1
fi

gpg --output "$2" --decrypt "$1"
