#!/usr/bin/env bash
#
# $$ GPGKITTY $$
# $$ cheap gpg magic for sexual powress $$
#
# import a key
#

. ./gpg-kitty

if [ -z "$1" ]; then
  usage; exit 1
fi

echo "
  \$\$\$
  magin kitty sp happy. you importing key:

  $1

  \$\$\$

"

gpg --import "$1"
gpg --list-keys
